### ISSUE TITLE
你在干嘛？？？？？？？

### ISSUE THREAD

**Issue by qaqFei** [114514fuckyou/lxeic#1]
https://114514fuckyou.github.io/lxeic/down.htm

![微信截图_20240905212429](https://github.com/user-attachments/assets/42831b85-5981-4521-bc10-fcc804feb75c)
？
原仓库: https://github.com/qaqFei/BiliClear

诉求: 删除相关内容

**Comment by 114514fuckyou** [comment]
已经根据作者要求删除
________________________________
发件人: qaqFei ***@***.***>
发送时间: 2024年9月5日 21:26
收件人: 114514fuckyou/lxeic ***@***.***>
抄送: Subscribed ***@***.***>
主题: [114514fuckyou/lxeic] 你在干嘛？？？？？？？ (Issue #1)


https://114514fuckyou.github.io/lxeic/down.htm

_20240905212429.png (view on web)<https://github.com/user-attachments/assets/42831b85-5981-4521-bc10-fcc804feb75c>
？
原仓库: https://github.com/qaqFei/BiliClear

诉求: 删除相关内容

―

**Comment by qaqFei** [comment]
thanks

**Comment by 114514fuckyou** [comment]
祝你的BiliClear有一天被征用

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
